name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-package:
    name: "Build Package"
    runs-on: macos-latest
    strategy:
      matrix:
        xcode:
        - '11.3' # Swift 5.1
        - '11.7' # Swift 5.2
        - '12.4' # Swift 5.3
        - '12.5.1' # Swift 5.4
        - '13.2' # Swift 5.5
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
        with:
          xcode: ${{ matrix.xcode }}
      - name: Build Package
        run: bundle exec rake build:iOS

  test-package-iOS:
    name: "Test Package (iOS)"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - name: Test Package
        run: bundle exec rake test:iOS
        
  test-package-macOS:
    name: "Test Package (macOS)"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - name: Test Package
        run: bundle exec rake test:macOS

  test-package-tvOS:
    name: "Test Package (tvOS)"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - name: Test Package
        run: bundle exec rake test:tvOS

  cocoapod:
    name: "Lint CocoaPods podspec"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
        with:
          install-mint: false
      - name: Lint CocoaPod Podspec
        run: bundle exec rake lint:podspec
